### ISSUE TITLE
Heavy swapping on first run

### ISSUE THREAD

**Issue by faveoled** [flathub/io.github.libredirect.frontends-manager#3]
I have 8 GB of RAM on my laptop.
On the first run the app ate all my memory and got into swap making my laptop unusable

**Comment by ManeraKai** [comment]
Can you show me the processes running on your computer? Like so:
![image](https://github.com/flathub/io.github.libredirect.frontends-manager/assets/40805353/fe2f3187-63a4-4a25-9e53-6d26f3f64b57)

**Comment by faveoled** [comment]
![image](https://github.com/flathub/io.github.libredirect.frontends-manager/assets/85760289/b4062015-529d-4468-8d31-1a4bb0cb40ab)

**Comment by faveoled** [comment]
This got filtered out:
![image](https://github.com/flathub/io.github.libredirect.frontends-manager/assets/85760289/21d51e31-bf47-42ff-831b-3341399f9cd4)

**Comment by faveoled** [comment]
> It's not using 8GB of ram though.

"on first run". Screenshots aren't. There was some subwindow that looked like a download on the first run without clicking anything beforehand

**Comment by ManeraKai** [comment]
It's installing caddy, the server that will reverse proxy the frontends. The RAM spike happened to me too.

**Comment by ManeraKai** [comment]
I fixed it for caddy, but there's a room for improvement for the frontends downloading too.
